### ISSUE TITLE
Breakage when comments are present

### ISSUE THREAD

**Issue by pangyre** [jhthorsen/plack-middleware-ssi#2]
I haven't done a test case but the parser fails when there is a regular html comment  following upon a valid ssi. This simple tweak fixed it for me (perl 5.14.0).
-        if($$buf =~ s/$SSI_EXPRESSION_END//) {
-        if($$buf =~ s/\Q$SSI_EXPRESSION_END//) {

Thank you so much for doing this module!

**Comment by jhthorsen** [comment]
Closing this because it's super old.
