### ISSUE TITLE
version mismatch and contributor typo

### ISSUE THREAD

**Issue by bieron** [jhthorsen/plack-middleware-ssi#9]
Changes file mentions **0.15**
POD in lib/Plack/Middleware/SSI.pm says **0.14**
README says just **0.12**

Also, Changes file mentions me as bireon instead of bieron.

Neither of these issues in my opinion warrant a new release, but please consider fixing the last one before the next (eventual) release.

**Comment by jhthorsen** [comment]
I suggest:
- Delete the README file and symlink lib/Plack/Middleware/SSI.pm to README.pod
- The Changes file track things that are not yet released, so the 0.15 and 0.14 diff is correct imo. I could be worth adding "0.15 Not Released" to the Changes file to make that more explicit and according to https://metacpan.org/pod/distribution/CPAN-Changes/lib/CPAN/Changes/Spec.pod#Date

**Comment by jhthorsen** [comment]
Closing this because it's super old.
